/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SettingsPanel.java
 *
 * Created on Mar 2, 2013, 9:48:28 PM
 */

package entryorganizer.gui;

import entryorganizer.Commander;

/**
 *
 * @author teopetuk89
 */
public class SettingsPanel extends javax.swing.JPanel {

    private Commander commander;
    
    /** Creates new form SettingsPanel */
    public SettingsPanel(Commander commander) {
        initComponents();
        this.commander = commander;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butBackup = new javax.swing.JButton();

        butBackup.setText("Бэкап");
        butBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBackupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butBackup)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butBackup)
                .addContainerGap(263, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void butBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBackupActionPerformed
    commander.getDataManager().backup();
}//GEN-LAST:event_butBackupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butBackup;
    // End of variables declaration//GEN-END:variables

}
